2nd hw is completed
fursserg/otus_hw pull request #2
Opened 2024-12-25 16:33 UTC by fursserg

## Домашнее задание №2 «Распаковка строки»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - unpack.go ~45 строк для задания без звездочки
  - unpack.go ~75 строк для задания со звездочкой

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2024-12-28 16:11 UTC, ityulkanov requested changes

2024-12-28 16:11 UTC, engineer-go commented on hw02_unpack_string/unpack.go
> +package main
название пакета менять нельзя, необходимо откатить эти изменения

2024-12-28 16:11 UTC, engineer-go commented on hw02_unpack_string/unpack.go
> +func main() {
необходимо удалить функцию main, т.к. вы пишете по сути либу, и main вам тут ни к чему. Для тестирования вы можете использовать тесты.

2024-12-28 16:11 UTC, ityulkanov commented on hw02_unpack_string/unpack.go
> +	var res []string
Не рекомендуется использовать result в виде слайса строк т.к. строки в go иммутабельны, и использование слайса с большим количеством распаковок приведёт к существенному увеличению использования хипа. 
к примеру даже простейшая распаковка  вроде a4bc2d5e, приведёт к созданию 5 строк.
a -> aaaa -> aaaab -> aaaabcc -> aaaabccddddde
Подсказка: необходимо использовать strings.Builder

2024-12-28 16:11 UTC, ityulkanov commented on hw02_unpack_string/unpack.go
> +func isNumeric(s string) (bool, int) {
В Go по конвенции необходимо возвращать ошибку пользователю, в вашем случае вы её просто мьютите, что не является хорошим тоном. Причем isNumeric вам вернёт true для символов вроде ১ что не является корректным поведением. Проще тут создать простейший if метод и проверять что 0 < x < 9

2024-12-28 16:11 UTC, ityulkanov commented on hw02_unpack_string/unpack_test.go
> +		{input: `qwe\\\3`, expected: `qwe\3`},
необходимо добавить corner cases от себя. Подсказка потестируейте варианты с двумя и трехбайтными utf символами, слешами в конце вроде `a2bcde\` пробелами в строке `a 4c`  и слешами вроде `\\32`

2025-01-06 09:18 UTC, fursserg commented on hw02_unpack_string/unpack.go
> +package main
Поправил

2025-01-06 09:20 UTC, fursserg commented on hw02_unpack_string/unpack.go
> +func main() {
Убрал

2025-01-06 09:42 UTC, fursserg commented on hw02_unpack_string/unpack.go
> +	var res []string
Переделал на использование strings.Builder вместо работы со слайсом строк. Но, если честно, то не понял что выиграл, т.к. strings.Builder внутри себя также работает со слайсом, правда не строк, а байт (не думаю, что принципиальная разница тут, т.к. сами элементы-строки я не изменял). При этом, сложность кода немного повысилась, т.к., используя strings.Builder, я лишился возможности удалять символы, а работая со слайсом строк, я мог просто заменять элемент на нужный.

2025-01-06 09:46 UTC, fursserg commented on hw02_unpack_string/unpack.go
> +func isNumeric(s string) (bool, int) {
Добавил возврат ошибки и модифицировал функцию - по идее, при любом раскладе, читая первый байт будет понятно, цифра ли лежит в строке из одного символа или что-либо еще.

2025-01-06 09:48 UTC, fursserg commented on hw02_unpack_string/unpack_test.go
> +		{input: `qwe\\\3`, expected: `qwe\3`},
Добавил

2025-01-09 05:45 UTC, ityulkanov approved these changes

2025-01-14 15:29 UTC, merged